<?xml version="1.0"?>
<package format="3">
  <name>apriltags</name>
  <version>0.0.0</version>
  <description>A catkin version of the C++ apriltags library based on OpenCV</description>

  <maintainer email="bianca.forkel@unibw.de">Bianca Forkel</maintainer>

  <author>Michael Kaess</author>
  <author>Hordur Johannson</author>
  <author>Hamphrey Hu</author>
  <author>Mitchell Wills</author>

  <license>LGPLv2.1</license>

  <url type="website">https://github.com/Humhu/apriltags/</url>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend>libopencv-dev</depend>

  <depend condition="$ROS_VERSION == 1">cmake_modules</depend>
  <depend condition="$ROS_VERSION == 1">eigen</depend>
  <depend condition="$ROS_VERSION == 1">libv4l-dev</depend>

  <depend condition="$ROS_VERSION == 2">eigen3_cmake_module</depend>

  <export>
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
