<?xml version="1.0"?>
<package format="3">
  <name>apriltags_tas</name>
  <version>0.0.0</version>
  <description>The apriltags_tas package</description>

  <maintainer email="bianca.forkel@unibw.de">Bianca Forkel</maintainer>
  <author email="bianca.forkel@unibw.de">Bianca Forkel</author>
  <author email="jan.kallwies@unibw.de">Jan Kallwies</author>
  <license>BSD</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <depend condition="$ROS_VERSION == 1">roscpp</depend>
  <depend condition="$ROS_VERSION == 1">dynamic_reconfigure</depend>
  <depend condition="$ROS_VERSION == 1">tf</depend>

  <depend condition="$ROS_VERSION == 2">rclcpp</depend>
  <depend condition="$ROS_VERSION == 2">rcl_interfaces</depend>
  <depend condition="$ROS_VERSION == 2">yaml-cpp</depend>

  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>image_geometry</depend>
  <depend>image_transport</depend>
  <depend>tf2_ros</depend>
  <depend>cv_bridge</depend>
  <depend>apriltags</depend>
  <depend>apriltags_msgs</depend>

  <export>
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>

</package>
